### ISSUE TITLE
files to delete

### ISSUE THREAD

**Issue by uzsolt** [bbqsrc/bandar#1]
I tried unionfs some time ago to maintaining ports.
I ran into a problem and I don't know how can solve it:
- you've `/usr/ports/cat/foo` port and it has patches, in directory `files/`
- you want upgrade this port to a newer version and the patches unneeded
  You'll copy this directory to `/usr/ports-devel` and remove the `files/` directory (in the `ports-devel`).
  `mount unionfs /usr/ports,/usr/ports-devel /usr/ports-union` you'll see the unwanted `files/` directory.

I think it'll problem in `bandar` too.

**Comment by bbqsrc** [comment]
unionfs-fuse specifically handles this case. [See this chunk of the man page.](https://github.com/rpodgorny/unionfs-fuse/blob/master/man/unionfs.8#L42-L49)
